name: Build and Push React App Docker Image
on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your desired AWS region

      - name: Install Node.js and npm
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Build React App
        run: |
          cd react-app  # Replace with the actual path to your React app
          npm install
          npm run build

      - name: Log in to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd react-app  # Replace with the actual path to your React app
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app-image:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app-image:latest
